### PR TITLE
Fix for DiscordExperiments

### PR DESCRIPTION
**Pull request by Aholicknight**
Replaced line 18 with 
```
const nodes = Object.values(settingsStore.default._dispatcher._actionHandlers._dependencyGraph.nodes);
```

This fixes DiscordExperiments and works again.

### CODE REVIEW

**Comment by XxUnkn0wnxX** [comment]
I can confirm working on Stable|PTB - 15.08.2022
_Till they nuke it again..._

**Comment by Inve1951** [comment]
There's rumors that the next time they break it, it will be locked server-side. As-in, even if you get the UI to work, the actual experiments won't.

**Comment by Aholicknight** [comment]
> There's rumors that the next time they break it, it will be locked server-side. As-in, even if you get the UI to work, the actual experiments won't.

@Inve1951 Is there proof that they will actually do this?

**Review by TechnoStone — APPROVED** [review]
Works on Stable 1.0.9006

**Comment by Aholicknight** [comment]
@Inve1951 can this please be merged since @TechnoStone confirms it works?

**Comment by Inve1951** [comment]
Adding any visibility to these fixes will only get them broken sooner. It's best to have it sitting here as a PR, if even that.
Side note: because i've removed the addon from the BD website, there's no such thing as an *official* version.

**Comment by Aholicknight** [comment]
If this pull request will sit here indefinitely then I will close this.

**Comment by Aholicknight** [comment]
Recent discord update breaks experiments _again_

**Comment by roblox34** [comment]
``let wpRequire;
window.webpackChunkdiscord_app.push([[ Math.random() ], {}, (req) => { wpRequire = req; }]);
mod = Object.values(wpRequire.c).find(x => typeof x?.exports?.Z?.isDeveloper !== "undefined");
usermod = Object.values(wpRequire.c).find(x => x?.exports?.default?.getUsers)
nodes = Object.values(mod.exports.Z._dispatcher._actionHandlers._dependencyGraph.nodes)
try {
    nodes.find(x => x.name == "ExperimentStore").actionHandler["OVERLAY_INITIALIZE"]({user: {flags: 1}})
} catch (e) {}
oldGetUser = usermod.exports.default.__proto__.getCurrentUser;
usermod.exports.default.__proto__.getCurrentUser = () => ({isStaff: () => true})
nodes.find(x => x.name == "DeveloperExperimentStore").actionHandler["CONNECTION_OPEN"]()
usermod.exports.default.__proto__.getCurrentUser = oldGetUser``

**Comment by Coder-Tavi** [comment]
Prettified so we can figure out @roblox34 is doing. I tested it on Stable and instantly got hit with a WS Code 1000 (Disconnect from Discord) after running the line about setting the staff to return true
```js
let wpRequire;
window.webpackChunkdiscord_app.push([[ Math.random() ], {}, (req) => { wpRequire = req; }]);
mod = Object.values(wpRequire.c).find(x => typeof x?.exports?.Z?.isDeveloper !== "undefined");
usermod = Object.values(wpRequire.c).find(x => x?.exports?.default?.getUsers);
nodes = Object.values(mod.exports.Z._dispatcher._actionHandlers._dependencyGraph.nodes);
try {
  nodes.find(x => x.name == "ExperimentStore").actionHandler["OVERLAY_INITIALIZE"]({user: {flags: 1}})
} catch (e) { };
oldGetUser = usermod.exports.default.__proto__.getCurrentUser;
usermod.exports.default.__proto__.getCurrentUser = () => ({isStaff: () => true});
nodes.find(x => x.name == "DeveloperExperimentStore").actionHandler["CONNECTION_OPEN"]();
usermod.exports.default.__proto__.getCurrentUser = oldGetUser
```

I'll toy around and figure out how to get this to work. Interesting stuff hidden inside the client.

**Comment by Soulivan71** [comment]
Anyone has a fix ?

**Pull request closed without merging**
