### PR TITLE
Update linkProfilePicture and AvatarHover

### PR DESCRIPTION
**Pull request by CompletelyUnbelievable**
EDIT: Here are the direct download links for my forks of the [LinkProfilePicture](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/CompletelyUnbelievable/BetterDiscordStuff-1/master/plugins/linkProfilePicture.plugin.js) and [AvatarHover](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/CompletelyUnbelievable/BetterDiscordStuff-1/master/plugins/AvatarHover.plugin.js) plugins.

I was surprised to see how little there was to the linkProfilePicture plugin, but it's also b/c of that I just rewrote it.

### CODE REVIEW

**Comment by CompletelyUnbelievable** [comment]
Updating Avatar hover quite irritating since I had to log everything that was being hovered to figure out why it wasn't detecting matches correctly after updating the classes. A parent is being hovered most of the time instead of the element with the img/BGimg, so I had to tell it to match the parent that would be hovered and then change the target to the element with the image based on an array of classes later.

**Comment by Inve1951** [comment]
Thanks for this PR. I see for AH you only updated the js file, the source is found [here](https://github.com/Inve1951/BetterDiscordStuff/blob/master/coffee/AvatarHover.plugin.coffee).
I'll test and review your changes soonish.

**Comment by CompletelyUnbelievable** [comment]
I could try and replicate the changes I've made onto the source but I am unfamiliar with CoffeeScript.

**Comment by CompletelyUnbelievable** [comment]
All I know is that I did enough right to get it to compile into JS, no idea if I did it properly.

**Comment by w4tchdoge** [comment]
I've checked [commit 3a9244e](https://github.com/Inve1951/BetterDiscordStuff/pull/65/commits/3a9244e56e303bfc9cf885e7634252eec3aadf00) on BD and it seems to work fine, any ETA on the PR merge?

**Comment by CompletelyUnbelievable** [comment]
3a9244e is a commit for linkProfilePicture, this pull request also consists of AvatarHover related files in JS and CoffeeScript that need to be checked by Square. Give Square some more time, they've been busy lately. Though it is good to know that things are working as intended on someone else's end.

**Comment by Inve1951** [comment]
Feel free to use this PR prior merge @w4tchdoge.

**Comment by Inve1951** [comment]
Thanks, @CompletelyUnbelievable.
Closing in favor of 1263bc5a.

**Pull request closed without merging**
