### PR TITLE
Update linkProfilePicture.plugin.js

### PR DESCRIPTION
**Pull request by BadScribbles**

### CODE REVIEW

**Comment by manchyy** [comment]
Thank you for such a simple fix :D

**Comment by TheGameratorT** [comment]
#184 bro 💀

**Review by Ketris — CHANGES_REQUESTED** [review]
This bandaid lets the plugin compile, but doesn't actually make asking it to stop running do anything.

I would instead suggest:
```
  stop () {
	document.removeEventListener.bind(document, "click", LinkProfilePicture, true);
  }
```

**Comment by BadScribbles** [comment]
Might you have missed line 16 which came with the original code ?
The new BD update requires plugins to have a stop function, not the functionality. Satisfying a requirement without changing old code is always a preference.

**Comment by Ketris** [comment]
Not including actual functionality within _stop()_ makes the plugin make multiple hooks into the click action if you load/unload the plugin repeatedly, which will cause multiple copies of the link to get opened with a single click.

**Comment by BadScribbles** [comment]
I'm not sure where you're getting these claims from, but everything you described is false. 
I was just trying to help and this seems to be starting to become an unnecessary argument over pitiful things. I will no longer replay to this.

**Comment by CompletelyUnbelievable** [comment]
> Not including actual functionality within _stop()_ makes the plugin make multiple hooks into the click action if you load/unload the plugin repeatedly, which will cause multiple copies of the link to get opened with a single click.

I don't notice such behavior after testing it. But I did also have to change it for it to work properly as stated in #184. I did also see Scribbles' deleted reply a moment ago. Anyways I'd still approve #184 after they fix that one bit I pointed out that recently changed.

**Comment by BadScribbles** [comment]
YES, I had to actually get back into this, since I've seen broken code being shared as working and branded as better while it was itself broken as illustrated here #183 

I can't believe making a pull request to solve an issue could blew up into all this for whatever reason. it's not like I'm saying the other suggested answer is bad, in fact it's much more clean and follows propre semantics, However i thought I'd share this little fix since it's doesn't change much from the original code and follows the original dev way of doin things.

**Comment by TheGameratorT** [comment]
JavaScript moment

**Comment by PrototypeGR** [comment]
Still doesn't work?

**Comment by kmidm21iomiodaw** [comment]
> Still doesn't work?

Just manually add an empty stop function inside the `linkProfilePicture` class like this:

`
module.exports = class linkProfilePicture {
    start() {
    ...
    }
    stop() {}
}
`

**Comment by PrototypeGR** [comment]
> module.exports = class linkProfilePicture { start() { ... } stop() {} }

image

Do i need to remove anything from line 12 or anything else?

**Comment by kmidm21iomiodaw** [comment]
> Do i need to remove anything from line 12 or anything else?

Uhh just copy paste from this pastebin instead. https://pastebin.com/B6nUFvQ2

**Comment by PrototypeGR** [comment]
> > Do i need to remove anything from line 12 or anything else?
> 
> Uhh just copy paste from this pastebin instead. https://pastebin.com/B6nUFvQ2

It doesn't show any error at start but even if you click on the avatars it won't open bigger either.

**Comment by kmidm21iomiodaw** [comment]
Is the script actually enabled in the plugins section?

**Comment by PrototypeGR** [comment]
Yes

**Comment by kmidm21iomiodaw** [comment]
Idk then it is interfering with a different plugin or something. It's
working perfectly fine for me with the same copy pasted code.

**Comment by Inve1951** [comment]
thx

**Pull request merged**
