### PR TITLE
[Link-Profile-Picture] Fix compatibility with latest BetterDiscord

### PR DESCRIPTION
**Pull request by TheGameratorT**
Fully tested.
Enabling and disabling the plugin is working as intended.

### CODE REVIEW

**Review by Ketris — APPROVED** [review]

**Comment by CompletelyUnbelievable** [comment]
Line 20 should be changed from `target.parentElement?.parentElement?.classList.contains("header-S26rhB"))` to `target.closest(".header-S26rhB"))`. Unless you want to add yet another `.parentElement?` since it's 3 parents away instead of 2.

**Comment by TheGameratorT** [comment]
Well that part was just code that was already written for the previous version. I enabled edits by maintainers if you guys want to change it, but I can tell if it'll work.

**Comment by Inve1951** [comment]
merged #185

**Comment by TheGameratorT** [comment]
Literally accepts the repo with unnatural looking code that redefines the stop() function whenever it's executed over the one with correctly defined code that follows the actual template structure.

**Comment by Inve1951** [comment]
i accepted #185 cause it had the simplest fix is all
this one is fine too obviously

**Pull request closed without merging**
