### PR TITLE
Fix `Compact-User-List`

### PR DESCRIPTION
**Pull request by LewsTherinTelescope**

### CODE REVIEW

**Comment by Inve1951** [comment]
That's cool, thanks.
Wanna bump the version (major or minor) and add yourself as an author?
It also seems like the avatar scaling causes the image to blur. Therefor the zoom should probably be an option.

**Comment by LewsTherinTelescope** [comment]
Hm, that's odd, not blurring for me. Is it just when it's expanded, or also when it's collapsed? I'll extract both to variables so they can be toggled easier, but just a warning that it doesn't look very nice in thin strip mode if it's not scaled up.

I'll play around with things a bit more and see if I can get it to adapt better.

**Comment by LewsTherinTelescope** [comment]
Alright, latest commit has scaling off by default but pretty easy to turn on. Also cuts down on the animations and transforms some, hadn't thought to try the previous fix on a proper large server and immediately regretted it when I did lol.

**Comment by Inve1951** [comment]
Sorry for the long delay. Thanks.

**Pull request merged**
