### PR TITLE
Fix profile picture size regex

### PR DESCRIPTION
**Pull request by pixel5718**
Regex was not replacing size=96 and link was looking like this: ".webp?size=96?size=4096".

### CODE REVIEW

**Comment by Inve1951** [comment]
How have you encountered such a small pfp? The only one being looked at is the one in the profile modal header, which is pretty big.

Did I not consider some setting?

**Comment by pixel5718** [comment]
I have no idea if there is some settings which makes it 96. When i open my own profile picture i get this link: https://cdn.discordapp.com/avatars/447472545739046913/0c36bea7c70305cf706e95dde640d9b0.webp?size=96?size=4096

**Comment by pixel5718** [comment]
I found which setting is doing that:
Apperance -> Zoom Level
On 50% it use 60px avatars
On 67-75% it use 96px avatars
80-100% use three digits size so regex is working for it but on lower zooms this plugin isn't working correctly

**Comment by Inve1951** [comment]
sry for the delay
it slipped my mind - just wanted to bump the version before merge
thx :+1:

**Pull request merged**
