### PR TITLE
directDownload Fixed opening file due to electron

### PR DESCRIPTION
**Pull request by rakosi2**
https://github.com/electron/governance/blob/master/wg-api/spec-documents/shell-openitem.md

### CODE REVIEW

**Comment by UnEnanoMas** [comment]
It does not work, same problem than #125

**Comment by daniel232005** [comment]
no puedo descargarlo :/

**Comment by Inve1951** [comment]
This API is no longer accessibly by BD plugins due to electron *security* changes. I'll revisit the issue once https://github.com/rauenzi/BetterDiscordApp/pull/842 makes it into official BD.

**Comment by pozhiloy-enotik** [comment]
> 
> 
> This API is no longer accessibly by BD plugins due to electron _security_ changes. I'll revisit the issue once [BetterDiscord/BetterDiscord#842](https://github.com/BetterDiscord/BetterDiscord/pull/842) makes it into official BD.

So, it is merged. What now? How to fix directDownload ?

**Comment by Inve1951** [comment]
> So, it is merged. What now? How to fix directDownload ?

Usage of `require("electron").remote` has to disappear.
The `remote.dialog.*` usage can be replaced with `BdApi.openDialog` but it seems there's no equivalent for `shell.openItem`/`shell.showItemInFolder` yet.

**Comment by Inve1951** [comment]
oh sorry, didn't see this was a PR

**Pull request closed without merging**
